### PR TITLE
Issue/8

### LINKED ISSUE #8: Undefined index warning when adding the widget to your sidebar (prior to saving)
To reproduce:

1. Add a new discount widget to your sidebar.
2. Check your error logs.

```
[29-Jul-2021 10:36:27 UTC] PHP Warning:  Undefined array key "hide_exp" in EDD-Discount-Widget/edd-discount-widget.php on line 94
```

### PR DESCRIPTION
**Pull request by rwebster85**
Fixes #8

Proposed Changes:

1. Checked array indexes are set before assigning to variables.

### CODE REVIEW

File: edd-discount-widget.php [hunk 1]
```diff
@@ -43,12 +43,13 @@ function widget( $args, $instance ) {
...
-            $api_key        = $instance['api_key'];
-            $api_token      = $instance['api_token'];
-            $max_discounts  = ( is_numeric( $instance['max_discounts'] ) ? $instance['max_discounts'] : '5' );
-            $hide_exp       = $instance['hide_exp'];
-            $count = 0;
+            $site_url       = isset( $instance['site_url'] ) ? $instance['site_url'] : '';
+            $api_key        = isset( $instance['api_key'] ) ? $instance['api_key'] : '';
+            $api_token      = isset( $instance['api_token'] ) ? $instance['api_token'] : '';
+            $max_discounts  = isset( $instance['max_discounts'] ) ? $instance['max_discounts'] : '';
+            $max_discounts  = ( is_numeric( $max_discounts ) ? $max_discounts : '5' );
```
Comment (ashleyfae) [inline edd-discount-widget.php:50]: Can you combine this with the above? So:

```php
isset( $instance['max_discounts'] ) && is_numeric( $instance['max_discounts'] ) ? // etc..
```

File: edd-discount-widget.php [hunk 2]
```diff
@@ -43,12 +43,12 @@ function widget( $args, $instance ) {
...
-            $site_url       = $instance['site_url'];
-            $api_key        = $instance['api_key'];
-            $api_token      = $instance['api_token'];
-            $max_discounts  = ( is_numeric( $instance['max_discounts'] ) ? $instance['max_discounts'] : '5' );
-            $hide_exp       = $instance['hide_exp'];
-            $count = 0;
+            $site_url       = isset( $instance['site_url'] ) ? $instance['site_url'] : '';
+            $api_key        = isset( $instance['api_key'] ) ? $instance['api_key'] : '';
+            $api_token      = isset( $instance['api_token'] ) ? $instance['api_token'] : '';
+            $max_discounts  = isset( $instance['max_discounts'] ) && is_numeric( $instance['max_discounts'] ) ? $instance['max_discounts'] : '';
```
Comment (ashleyfae) [inline edd-discount-widget.php:49]:
```suggestion
            $max_discounts  = isset( $instance['max_discounts'] ) && is_numeric( $instance['max_discounts'] ) ? $instance['max_discounts'] : 5;
```

Default here looks to be `5`. :) (Don't think we need it as a string like it originally was though..)

**Review by ashleyfae — APPROVED** [review]
